version: '3'
services:
  frontend:
    build:
      context: ../
      dockerfile: dockerfiles/frontend/dockerfile
    ports:
      - "8001:5002"
    environment:
      - VITE_baseURL="http://backend:8000"
    networks:
      - main
  backend:
    build:
      context: ../
      dockerfile: dockerfiles/backend/dockerfile
    ports:
      - "8000:8000"
    networks:
      - main
networks:
  main: